### PR TITLE
README.md

### PR DESCRIPTION
**Pull request by aabowen**
Add OCF, The Open Connectivity Foundation, standards.

### CODE REVIEW

**Comment by HQarroum** [comment]
Hi, Thanks for the contribution!

OCF is replacing OIC (Open Interconnect) which is in the `Alliances` section. I think that it would be better to remove the OIC entry from this section first. and let OCF in the `Standards` section. I think it would be better to make this change in this pull request, since this is basically a replacement.

**Comment by aabowen** [comment]
Ok, shall I make those updates and submit a new PR?

**Comment by HQarroum** [comment]
Yes that would be really nice 😉. Thank you.

**Comment by HQarroum** [comment]
OCF has been added in PR #15.

**Pull request closed without merging**
